import {
  CarCategory,
  CarStatus,
  FuelType,
  Transmission,
} from '../../common/enums';

export interface CarSeedRow {
  brand: string;
  model: string;
  year: number;
  color: string;
  registrationNumber: string;
  vin: string;
  category: CarCategory;
  transmission: Transmission;
  fuelType: FuelType;
  seats: number;
  pricePerDay: number;
}

/** 20 voitures — Kia, Hyundai (i10/i20), Suzuki, Picanto — prix 140–200 TND */
export const AGENCY_CARS_SEED: CarSeedRow[] = [
  {
    brand: 'Kia',
    model: 'Picanto',
    year: 2023,
    color: 'Blanc',
    registrationNumber: '201TU1001',
    vin: 'KNAB2513APT100001',
    category: CarCategory.ECONOMY,
    transmission: Transmission.MANUAL,
    fuelType: FuelType.GASOLINE,
    seats: 5,
    pricePerDay: 140,
  },
  {
    brand: 'Kia',
    model: 'Picanto',
    year: 2022,
    color: 'Gris',
    registrationNumber: '202TU1002',
    vin: 'KNAB2513APT100002',
    category: CarCategory.ECONOMY,
    transmission: Transmission.AUTOMATIC,
    fuelType: FuelType.GASOLINE,
    seats: 5,
    pricePerDay: 155,
  },
  {
    brand: 'Kia',
    model: 'Picanto',
    year: 2024,
    color: 'Rouge',
    registrationNumber: '203TU1003',
    vin: 'KNAB2513APT100003',
    category: CarCategory.ECONOMY,
    transmission: Transmission.MANUAL,
    fuelType: FuelType.GASOLINE,
    seats: 5,
    pricePerDay: 145,
  },
  {
    brand: 'Kia',
    model: 'Picanto',
    year: 2021,
    color: 'Bleu',
    registrationNumber: '204TU1004',
    vin: 'KNAB2513APT100004',
    category: CarCategory.ECONOMY,
    transmission: Transmission.AUTOMATIC,
    fuelType: FuelType.GASOLINE,
    seats: 5,
    pricePerDay: 160,
  },
  {
    brand: 'Kia',
    model: 'Rio',
    year: 2023,
    color: 'Noir',
    registrationNumber: '205TU1005',
    vin: 'KNAB3513APT100005',
    category: CarCategory.COMPACT,
    transmission: Transmission.MANUAL,
    fuelType: FuelType.GASOLINE,
    seats: 5,
    pricePerDay: 175,
  },
  {
    brand: 'Kia',
    model: 'Rio',
    year: 2022,
    color: 'Blanc',
    registrationNumber: '206TU1006',
    vin: 'KNAB3513APT100006',
    category: CarCategory.COMPACT,
    transmission: Transmission.AUTOMATIC,
    fuelType: FuelType.GASOLINE,
    seats: 5,
    pricePerDay: 190,
  },
  {
    brand: 'Hyundai',
    model: 'i10',
    year: 2023,
    color: 'Blanc',
    registrationNumber: '207TU1007',
    vin: 'MALB2513APT100007',
    category: CarCategory.ECONOMY,
    transmission: Transmission.MANUAL,
    fuelType: FuelType.GASOLINE,
    seats: 5,
    pricePerDay: 142,
  },
  {
    brand: 'Hyundai',
    model: 'i10',
    year: 2024,
    color: 'Gris',
    registrationNumber: '208TU1008',
    vin: 'MALB2513APT100008',
    category: CarCategory.ECONOMY,
    transmission: Transmission.AUTOMATIC,
    fuelType: FuelType.GASOLINE,
    seats: 5,
    pricePerDay: 165,
  },
  {
    brand: 'Hyundai',
    model: 'i10',
    year: 2022,
    color: 'Orange',
    registrationNumber: '209TU1009',
    vin: 'MALB2513APT100009',
    category: CarCategory.ECONOMY,
    transmission: Transmission.MANUAL,
    fuelType: FuelType.GASOLINE,
    seats: 5,
    pricePerDay: 148,
  },
  {
    brand: 'Hyundai',
    model: 'i10',
    year: 2023,
    color: 'Bleu',
    registrationNumber: '210TU1010',
    vin: 'MALB2513APT100010',
    category: CarCategory.ECONOMY,
    transmission: Transmission.AUTOMATIC,
    fuelType: FuelType.GASOLINE,
    seats: 5,
    pricePerDay: 170,
  },
  {
    brand: 'Hyundai',
    model: 'i20',
    year: 2023,
    color: 'Blanc',
    registrationNumber: '211TU1011',
    vin: 'MALC2513APT100011',
    category: CarCategory.COMPACT,
    transmission: Transmission.MANUAL,
    fuelType: FuelType.GASOLINE,
    seats: 5,
    pricePerDay: 165,
  },
  {
    brand: 'Hyundai',
    model: 'i20',
    year: 2024,
    color: 'Gris',
    registrationNumber: '212TU1012',
    vin: 'MALC2513APT100012',
    category: CarCategory.COMPACT,
    transmission: Transmission.AUTOMATIC,
    fuelType: FuelType.GASOLINE,
    seats: 5,
    pricePerDay: 185,
  },
  {
    brand: 'Hyundai',
    model: 'i20',
    year: 2022,
    color: 'Rouge',
    registrationNumber: '213TU1013',
    vin: 'MALC2513APT100013',
    category: CarCategory.COMPACT,
    transmission: Transmission.MANUAL,
    fuelType: FuelType.GASOLINE,
    seats: 5,
    pricePerDay: 160,
  },
  {
    brand: 'Hyundai',
    model: 'i20',
    year: 2023,
    color: 'Noir',
    registrationNumber: '214TU1014',
    vin: 'MALC2513APT100014',
    category: CarCategory.COMPACT,
    transmission: Transmission.AUTOMATIC,
    fuelType: FuelType.GASOLINE,
    seats: 5,
    pricePerDay: 195,
  },
  {
    brand: 'Suzuki',
    model: 'Swift',
    year: 2023,
    color: 'Bleu',
    registrationNumber: '215TU1015',
    vin: 'JS2ZC53S0P100015',
    category: CarCategory.COMPACT,
    transmission: Transmission.MANUAL,
    fuelType: FuelType.GASOLINE,
    seats: 5,
    pricePerDay: 155,
  },
  {
    brand: 'Suzuki',
    model: 'Swift',
    year: 2024,
    color: 'Blanc',
    registrationNumber: '216TU1016',
    vin: 'JS2ZC53S0P100016',
    category: CarCategory.COMPACT,
    transmission: Transmission.AUTOMATIC,
    fuelType: FuelType.GASOLINE,
    seats: 5,
    pricePerDay: 180,
  },
  {
    brand: 'Suzuki',
    model: 'Swift',
    year: 2022,
    color: 'Gris',
    registrationNumber: '217TU1017',
    vin: 'JS2ZC53S0P100017',
    category: CarCategory.COMPACT,
    transmission: Transmission.MANUAL,
    fuelType: FuelType.GASOLINE,
    seats: 5,
    pricePerDay: 150,
  },
  {
    brand: 'Suzuki',
    model: 'Celerio',
    year: 2023,
    color: 'Rouge',
    registrationNumber: '218TU1018',
    vin: 'JS2ZC53S0P100018',
    category: CarCategory.ECONOMY,
    transmission: Transmission.AUTOMATIC,
    fuelType: FuelType.GASOLINE,
    seats: 5,
    pricePerDay: 145,
  },
  {
    brand: 'Suzuki',
    model: 'Ignis',
    year: 2022,
    color: 'Vert',
    registrationNumber: '219TU1019',
    vin: 'JS2ZC53S0P100019',
    category: CarCategory.COMPACT,
    transmission: Transmission.MANUAL,
    fuelType: FuelType.GASOLINE,
    seats: 5,
    pricePerDay: 172,
  },
  {
    brand: 'Suzuki',
    model: 'Dzire',
    year: 2023,
    color: 'Argent',
    registrationNumber: '220TU1020',
    vin: 'JS2ZC53S0P100020',
    category: CarCategory.SEDAN,
    transmission: Transmission.AUTOMATIC,
    fuelType: FuelType.GASOLINE,
    seats: 5,
    pricePerDay: 200,
  },
];
